# Generated by Django 2.1 on 2019-08-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20190809_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='white', max_length=100, verbose_name='カラー'),
        ),
    ]
