# Generated by Django 2.1 on 2019-08-23 05:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='body',
        ),
        migrations.AddField(
            model_name='contact',
            name='text',
            field=markdownx.models.MarkdownxField(default='hoge', verbose_name='本文'),
            preserve_default=False,
        ),
    ]
