# Generated by Django 2.1 on 2019-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30, verbose_name='分類')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('url', models.URLField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='順番')),
            ],
            options={
                'verbose_name': 'マニュアル',
                'verbose_name_plural': 'マニュアル',
                'db_table': 'manuals',
            },
        ),
    ]
