# Generated by Django 2.1 on 2019-08-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='category',
            field=models.CharField(default='ほげ', max_length=30, verbose_name='分類'),
            preserve_default=False,
        ),
    ]
