# Generated by Django 2.1 on 2019-09-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
