# Generated by Django 2.1.4 on 2019-01-06 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='場所')),
            ],
            options={
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='シート名')),
                ('date', models.DateField(verbose_name='実施日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効なシートかどうか')),
            ],
            options={
                'db_table': 'sheets',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='タスクの説明')),
                ('color', models.CharField(default='white', max_length=30, verbose_name='タスクの色')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shift.Place')),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(verbose_name='開始時刻')),
                ('is_now', models.BooleanField(verbose_name='現在時刻かどうか')),
            ],
            options={
                'db_table': 'times',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.Task'),
        ),
        migrations.AddField(
            model_name='cell',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.Time'),
        ),
        migrations.AddField(
            model_name='cell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
