# Generated by Django 2.1.4 on 2019-05-02 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'シフト',
                'verbose_name_plural': 'シフト',
                'db_table': 'cells',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='場所')),
                ('color', models.CharField(default='black', max_length=30, verbose_name='場所カラー')),
            ],
            options={
                'verbose_name': '場所',
                'verbose_name_plural': '場所',
                'db_table': 'places',
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='ex) 1日目, 片付け日', max_length=30, verbose_name='シート名')),
                ('date', models.DateField(verbose_name='実施日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効なシートかどうか')),
            ],
            options={
                'verbose_name': 'シート',
                'verbose_name_plural': 'シート',
                'db_table': 'sheets',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='タスク名')),
                ('description', models.TextField(blank=True, null=True, verbose_name='タスクの説明')),
                ('color', models.CharField(default='black', max_length=30, verbose_name='タスクの色')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shift.Place')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
                'db_table': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(unique=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(unique=True, verbose_name='終了時刻')),
                ('is_now', models.BooleanField(default=False, verbose_name='現在時刻かどうか')),
            ],
            options={
                'verbose_name': '時間帯',
                'verbose_name_plural': '時間帯',
                'db_table': 'times',
            },
        ),
        migrations.AddField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.Sheet'),
        ),
        migrations.AddField(
            model_name='cell',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.Task'),
        ),
        migrations.AddField(
            model_name='cell',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shift.Time'),
        ),
        migrations.AddField(
            model_name='cell',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('sheet', 'user', 'time')},
        ),
    ]
