# Generated by Django 2.1.4 on 2019-01-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='is_now',
            field=models.BooleanField(default=False, verbose_name='現在時刻かどうか'),
        ),
    ]
