# Generated by Django 2.1 on 2019-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='manual_url',
            field=models.CharField(default='', max_length=30, verbose_name='マニュアルURL'),
        ),
        migrations.AlterField(
            model_name='belong',
            name='order',
            field=models.IntegerField(verbose_name='優先順位'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='order',
            field=models.IntegerField(verbose_name='優先順位'),
        ),
    ]
