# Generated by Django 2.1 on 2019-09-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='manual_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='マニュアルURL'),
        ),
    ]
