# Generated by Django 2.1 on 2019-06-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': '実施場所', 'verbose_name_plural': '実施場所'},
        ),
    ]
