# Generated by Django 2.1 on 2019-08-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20190810_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belong',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='優先順位'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='優先順位'),
        ),
    ]
