# Generated by Django 2.1 on 2019-08-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20190807_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='white', max_length=30, verbose_name='タスクの色'),
        ),
    ]
