# Generated by Django 2.1 on 2019-08-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20190807_0720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cell',
            options={'verbose_name': 'セル', 'verbose_name_plural': 'セル'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'メンバー', 'verbose_name_plural': 'メンバー'},
        ),
    ]
