# Generated by Django 2.1 on 2019-08-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0003_auto_20190811_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='student_id',
        ),
    ]
