# Generated by Django 2.1.4 on 2019-01-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shift', '0003_auto_20190120_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shift.Sheet'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('sheet', 'user', 'time')},
        ),
    ]
