# Generated by Django 2.1 on 2019-08-08 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_auto_20190808_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='time',
            name='is_now',
        ),
    ]
