# Generated by Django 2.1 on 2019-08-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_remove_member_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheet',
            name='date',
        ),
    ]
