# Generated by Django 2.1 on 2019-08-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_remove_sheet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名前'),
        ),
    ]
