# Generated by Django 2.1 on 2019-08-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_auto_20190814_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='電話番号'),
        ),
    ]
