# Generated by Django 2.1 on 2019-08-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0007_member_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='電話番号'),
        ),
    ]
