# Generated by Django 2.1 on 2019-08-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0008_auto_20190814_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='day',
            field=models.IntegerField(default=14, verbose_name='日にち'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='weather',
            field=models.CharField(choices=[('晴', '晴'), ('雨', '雨')], default=1, max_length=10, verbose_name='天気'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sheet',
            name='name',
            field=models.CharField(max_length=30, verbose_name='シート名'),
        ),
    ]
