# Generated by Django 2.1 on 2019-08-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, verbose_name='トークン')),
                ('username', models.CharField(blank=True, max_length=30, null=True, verbose_name='ユーザ名')),
            ],
            options={
                'verbose_name': 'デバイストークン',
                'verbose_name_plural': 'デバイストークン',
                'db_table': 'device_tokens',
            },
        ),
    ]
