# Generated by Django 2.1 on 2019-09-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weather', models.CharField(choices=[('晴', '晴'), ('雨', '雨')], default='晴', max_length=10, verbose_name='天気')),
                ('api_mode', models.BooleanField(default=True, verbose_name='APIモードか')),
            ],
            options={
                'verbose_name': '共通オプション',
                'verbose_name_plural': '共通オプション',
                'db_table': 'options',
            },
        ),
    ]
